"""Outbound message queue — protocol + value types.

The outbound queue is the **single point of egress** for every customer-
facing message the system produces. Call sessions, retries, reminders —
everything funnels through ``OutboundQueue.enqueue(...)``. A separate
worker process (see ``guidepoint.outbound``) drains the queue FIFO and
applies two delivery gates: SMS consent, and business hours. Nothing
outside the worker reads those gates, so the rest of the system stays
hours-agnostic — the case state machine emits sends whenever its state
transitions say to, and the queue decides when they actually leave.

The queue is content-agnostic: it stores items, not policy. It does not
inspect the body, peek at case state, or check the clock. Worker
behaviour lives in ``guidepoint.outbound``; persistence behaviour lives
here. Tests for each can run independently.

Item lifecycle
==============

::

   enqueue ──► pending ──┐
                          │ (worker tick: hold_until <= now)
                          ▼
                       in_flight
                          │
              ┌───────────┼───────────────┬─────────────┐
              ▼           ▼               ▼             ▼
            sent        blocked         failed       pending
        (Twilio ok)  (consent gone)  (max attempts) (transient,
                                                     retry later)

``pending``, ``in_flight`` → terminal states ``sent``, ``blocked``,
``failed``. The worker is the only writer of state transitions; the
enqueueing call sites only ever produce ``pending`` rows.
"""

from __future__ import annotations

from enum import StrEnum
from typing import Literal, Protocol

from pydantic import BaseModel, ConfigDict, Field

from guidepoint.case._models import CaseId
from guidepoint.clock import UtcDatetime


class OutboundState(StrEnum):
    """Lifecycle states for an outbound queue item.

    See module docstring for the state diagram. Terminal states are
    ``SENT`` (success), ``BLOCKED`` (refused by policy), and ``FAILED``
    (exhausted retries on transient errors).
    """

    PENDING = "pending"
    IN_FLIGHT = "in_flight"
    SENT = "sent"
    BLOCKED = "blocked"
    FAILED = "failed"

    @property
    def is_terminal(self) -> bool:
        """``True`` when the item will not change state again."""
        return self in {OutboundState.SENT, OutboundState.BLOCKED, OutboundState.FAILED}


#: Item kind discriminator. Only ``sms_text`` exists in v1. Future kinds
#: (voice call hand-off, MMS, etc.) extend the union; the worker
#: dispatches by kind.
OutboundKind = Literal["sms_text"]


class OutboundItem(BaseModel):
    """One queued unit of work bound for a customer.

    All times are UTC. ``item_id`` is generated by the queue at enqueue
    time and is the durable handle every other system component uses to
    refer to this send. ``twilio_sid`` is populated by the worker after
    Twilio accepts the send (it is Twilio's identifier, not ours).

    The queue stores this as a row in ``outbound_queue``; readers never
    construct ``OutboundItem`` directly — they receive it from the
    queue. The model is frozen so a single instance can be safely shared
    across async tasks.
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    item_id: str = Field(min_length=1)
    case_id: CaseId
    kind: OutboundKind = "sms_text"
    to_phone: str = Field(min_length=1)
    body: str
    state: OutboundState
    enqueued_at: UtcDatetime
    hold_until: UtcDatetime
    claimed_at: UtcDatetime | None = None
    sent_at: UtcDatetime | None = None
    twilio_sid: str = ""
    attempts: int = Field(ge=0, default=0)
    max_attempts: int = Field(ge=1, default=3)
    last_error: str = ""


class OutboundQueue(Protocol):
    """Persistence protocol for the outbound message queue.

    Producers call :meth:`enqueue`. The worker calls
    :meth:`claim_next_ready` then exactly one of :meth:`mark_sent`,
    :meth:`mark_blocked`, or :meth:`mark_retry` / :meth:`mark_failed`.

    All methods are synchronous because SQLite is. Callers that need to
    yield to the event loop wrap calls in ``asyncio.to_thread``; the
    worker does this for its tick loop.
    """

    def enqueue(
        self,
        *,
        case_id: CaseId,
        to_phone: str,
        body: str,
        enqueued_at: UtcDatetime,
        hold_until: UtcDatetime | None = None,
        max_attempts: int = 3,
        kind: OutboundKind = "sms_text",
    ) -> OutboundItem:
        """Add a new ``PENDING`` item to the queue.

        ``hold_until`` defaults to ``enqueued_at`` (immediate). Returns
        the freshly persisted item, including the queue-assigned
        ``item_id``. Never raises for queue-related reasons — schema
        errors propagate as ``sqlite3.DatabaseError``.
        """
        ...

    def claim_next_ready(self, *, now: UtcDatetime) -> OutboundItem | None:
        """Atomically claim the oldest ``PENDING`` item with ``hold_until <= now``.

        On success the item moves to ``IN_FLIGHT`` with ``claimed_at = now``
        and is returned. Returns ``None`` when nothing is ready (queue
        empty or all pending items are still held). The worker calls this
        on every tick.
        """
        ...

    def mark_sent(
        self,
        *,
        item_id: str,
        twilio_sid: str,
        sent_at: UtcDatetime,
    ) -> OutboundItem:
        """Move a claimed item to ``SENT`` and record Twilio's MessageSid."""
        ...

    def mark_blocked(self, *, item_id: str, reason: str) -> OutboundItem:
        """Move a claimed item to ``BLOCKED`` (consent / policy refused).

        Terminal — the worker will not retry. ``reason`` lands in
        ``last_error`` for forensics.
        """
        ...

    def mark_retry(
        self,
        *,
        item_id: str,
        retry_at: UtcDatetime,
        last_error: str,
    ) -> OutboundItem:
        """Return a claimed item to ``PENDING`` with a future ``hold_until``.

        Increments ``attempts``. Caller is responsible for deciding
        whether to retry vs. give up (compare ``attempts`` to
        ``max_attempts`` after this call's effect; if exhausted, call
        :meth:`mark_failed` instead).
        """
        ...

    def mark_failed(self, *, item_id: str, last_error: str) -> OutboundItem:
        """Move a claimed item to ``FAILED`` (max attempts exhausted)."""
        ...

    def reclaim_stale_in_flight(
        self,
        *,
        older_than: UtcDatetime,
    ) -> int:
        """Reset ``IN_FLIGHT`` rows claimed before ``older_than`` back to ``PENDING``.

        Run once at startup (and optionally on a slow background tick)
        to recover from worker crashes that left items orphaned. Returns
        the number of rows reclaimed.
        """
        ...

    def get(self, item_id: str) -> OutboundItem | None:
        """Forensics: fetch a single item by id, regardless of state."""
        ...

    def list_for_case(self, case_id: CaseId) -> tuple[OutboundItem, ...]:
        """Forensics: every item ever enqueued for a case, in enqueue order."""
        ...

    def pending_depth(self) -> int:
        """Total number of items currently in ``PENDING`` state. For ops."""
        ...


__all__ = [
    "OutboundItem",
    "OutboundKind",
    "OutboundQueue",
    "OutboundState",
]
